#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

# route pour récupérer le token jwt à partir des credentials (login / password)
jwt_login:
    path: /api/login
